apiVersion: v1
kind: Pod
metadata:
  name: demo
  labels:
    app: demo
spec:
  containers:
  - name: demo-container
    image: satish2323/demo-project:v2
    ports:
      - containerPort: 8082
