apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort
  selector:
    app: demo
  ports:
  - name: demo-port
    protocol: TCP
    port: 8082
    targetPort: 8082
    nodePort: 30082